import logging

from agent.tools.get_cart import get_cart
from agent.tools.find_products import find_products
from agent.tools.add_to_cart import add_to_cart
from dto.tool_context import ToolContext

_logger = logging.getLogger("tools.executor")


class ToolExecutor:
    """Executes tools requested by the language model.

    Provides a controlled layer between the LLM and application tools.
    Injects runtime context (such as user identity) into tool calls
    and prevents the model from accessing internal application details.
    """

    def __init__(self, context: ToolContext):
        """Initialize tool executor.

        Args:
            context (ToolContext): Runtime context of the current user session.
        """
        self.context = context

    def execute(
        self,
        tool_name: str,
        arguments: dict,
    ):
        """Execute a tool requested by the language model.

        Args:
            tool_name (str): Name of the tool to execute.
            arguments (dict): Arguments provided by the language model.

        Returns:
            Any: Result returned by the executed tool.

        Raises:
            ValueError: If the requested tool does not exist.
        """
        tool = getattr(self, f"_{tool_name}", None)

        if tool is None:
            raise ValueError(f"Unknown tool: {tool_name}")

        _logger.info(
            "Executing tool %s with args %s",
            tool_name,
            arguments,
        )

        return tool(**arguments)

    def _add_to_cart(self, **arguments):
        return add_to_cart(user_id=self.context.user_id, **arguments)

    def _get_cart(self):
        """Get the current user's active shopping cart.

        The user identifier is taken from the execution context and
        is not provided by the language model.

        Returns:
            dict: User's active cart.
        """
        return get_cart(user_id=self.context.user_id)

    def _find_products(self, **arguments) -> list:
        """Search products using provided arguments.

        Args:
            arguments: Parameters generated by the language model.

        Returns:
            list: Matching products.
        """
        return find_products(**arguments)
