import logging

import aiohttp
from aiohttp import web

from aiogram import Bot, Dispatcher
from aiogram.webhook.aiohttp_server import SimpleRequestHandler, setup_application


from config import bot_config

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)

_logger = logging.getLogger("bot.logger")

bot = Bot(token=bot_config.token)
dp = Dispatcher()


async def get_ngrok_url() -> str:
    """Gets the url generated by ngrok.

    Returns:
        str: url generated by ngrok.
    """
    async with aiohttp.ClientSession() as session:
        async with session.get("http://127.0.0.1:4040/api/tunnels") as response:
            data = await response.json()

    return data["tunnels"][0]["public_url"]


async def on_startup(bot: Bot) -> None:
    """Installing the webhook when launching the application.

    Args:
        bot (Bot): aiogram Bot instance.
    """

    webhook_url = bot_config.webhook_url
    if webhook_url == "debug":
        webhook_url = await get_ngrok_url()

    await bot.set_webhook(f"{webhook_url}{bot_config.webhook_path}")


async def start_bot() -> None:
    """Starts the Telegram bot webhook server.

    Configures the aiogram dispatcher, registers startup handlers,
    creates and configures the aiohttp application, registers the
    webhook request handler, and starts the HTTP server that receives
    webhook updates from Telegram.
    """
    dp.startup.register(on_startup)

    app = web.Application()

    webhook_requests_handler = SimpleRequestHandler(
        dispatcher=dp,
        bot=bot,
    )
    webhook_requests_handler.register(
        app,
        path=bot_config.webhook_path,
    )
    setup_application(app, dp, bot=bot)

    await web._run_app(
        app,
        host="127.0.0.1",
        port=8080,
    )
